IF OBJECT_ID('dbo.users', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.users (
        id INT IDENTITY(1,1) PRIMARY KEY,
        username NVARCHAR(50) NOT NULL UNIQUE,
        email NVARCHAR(255) NOT NULL UNIQUE,
        password_hash NVARCHAR(512) NOT NULL,
        created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
        skills NVARCHAR(2000),
        experience NVARCHAR(4000),
        profile_picture VARBINARY(MAX)
    );
END
ELSE
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='users' AND COLUMN_NAME='skills')
    BEGIN
        ALTER TABLE dbo.users ADD skills NVARCHAR(2000);
    END;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='users' AND COLUMN_NAME='experience')
    BEGIN
        ALTER TABLE dbo.users ADD experience NVARCHAR(4000);
    END;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='users' AND COLUMN_NAME='profile_picture')
    BEGIN
        ALTER TABLE dbo.users ADD profile_picture VARBINARY(MAX);
    END;
END;

